name: moodstamp
description: Minimalistic mood tracker for iOS and Android

version: 1.0.0+1

environment:
  sdk: ">2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    #    - family: Raleway
    #      fonts:
    #        - asset: fonts/Raleway-Regular.ttf
    #        - asset: fonts/Raleway-Italic.ttf
    #          style: italic
    #    - family: RobotoMono
    #      fonts:
    #        - asset: fonts/RobotoMono-Regular.ttf
    #        - asset: fonts/RobotoMono-Bold.ttf
    #          weight: 700
    - family: Gidole
      fonts:
        - asset: asset/font/Gidole-Regular.ttf