spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: moodstamp
server:
  port: 8080
security:
  token:
    secret-key: 'ababababba'
    expiration-time: 864000000
    header:
      name: 'jwt-token'