spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: moodstamp
server:
  port: 8080
security:
  token:
    #intentionally public
    secret-key: 'super-secret key'
    expiration-time: 864000000
    header:
      name: 'Jwt-Token'